/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-11-10 19:18:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    \r\n");
 

if(session.getAttribute("usuario") == null) {
	out.println("<meta http-equiv='refresh' content ='0;url=login.jsp'>");
}

if(session.getAttribute("anio") == null) {session.setAttribute("anio", 2014);}
if( session.getAttribute("mes") == null)   {session.setAttribute("mes",9);}
int mesnumero = (Integer)(session.getAttribute("mes"));
if (request.getParameter("mes") !=null) if (request.getParameter("mes").contains("anterior")){session.setAttribute("mes", mesnumero-1);}
if (request.getParameter("mes") !=null) if (request.getParameter("mes").contains("posterior")){session.setAttribute("mes", mesnumero+1);}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>\r\n");
      out.write("\t\t\tSeptiembre2014 ---++++++------ ");
out.println(session.getAttribute("mes"));  
      out.write("\t\t\r\n");
      out.write("\t\t</title>\t\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<script src=\"./lib/jquery-1.10.1.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"./lib/jquery-ui.js\"></script>\r\n");
      out.write("\t\t<script src=\"./js/codigo.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/estilo.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/header.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<div id=\"tituloprint\">www.webcalendario.com</div>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<h1>webcalendario.com</h1>\r\n");
      out.write("\t\t\t\t<h2>Tu calendario en la nube</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\tInicio\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\tFAQ\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li id=\"botonlogin\">\r\n");
      out.write("\t\t\t\t\t\tInicia sesionñ\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li id=\"botonsignin\">\r\n");
      out.write("\t\t\t\t\t\tRegístrate\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li id=\"contacto\">\r\n");
      out.write("\t\t\t\t\t\tContacto\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li id=\"contacto\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">Cerrar Sesion</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<table width=\"100%\">\r\n");
      out.write("\t<tbody><tr>\r\n");
      out.write("\t<td id=\"aniotitulo\">\r\n");
      out.write("\t\t<h2>");
out.println(session.getAttribute("mes"));
      out.write("</h2><h1>");
out.println(session.getAttribute("anio")); 
      out.write("</h1></td>\r\n");
      out.write("\t\t<td id=\"botones\">\r\n");
      out.write("\t\t\t<a href=\"?mes=anterior\"><button> &lt;&lt; </button></a>\r\n");
      out.write("\t\t\t<a href=\"?mes=posterior\"><button> &gt;&gt; </button></a>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<div id=\"calendarios\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");

			 try  {
				 
				 
		
				 
				 
				 String conexion ="jdbc:mysql://localhost:3306/webcalendario";
				
				 Connection connection = null;
				 Class.forName("com.mysql.jdbc.Driver").newInstance();
				
				 connection =DriverManager.getConnection(conexion,"web","calendario");
				 
				 Statement stat = connection.createStatement();
				 ResultSet rset;
				 
				 String peticion ="SELECT * FROM calendarios WHERE usuario =" + session.getAttribute("idusuario") + ";";
				 rset = stat.executeQuery(peticion);
				 
				 out.println(peticion);
				  
				 while(rset.next()){
					 
					  out.println("<span class='calendariocol' idcalendario='1' style='width:80px;background:rgb("+ rset.getString("color") +");'>" +rset.getString("nombre")+ " - <a href='acciones/eliminarCalendario.jsp?idcalendario=" + rset.getInt("idcalendario")   +" class='cierracalendarioX'>X</a>  </span>");
				 }	  
				 				 
				 stat.close();
				 connection.close();
				
				 
			 } catch(Exception ex ){
		
			 out.println("Ha ocurrido el siguiente error"+ ex.getMessage().toString());
			 }
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button id=\"botonanadircalendario\">Añadir calendario</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<span class=\"calendariocol\" style=\"background:grey;\" id=\"ocultacalendarios\"> &gt; </span>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</tbody></table>\r\n");
      out.write("\t\t<div style=\"clear:both;\"></div>\r\n");
      out.write("\t\t<div id=\"calendario\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
 	 try  {
				 
			
				 int desfase =0;
				 if  (session.getAttribute("mes").toString().equals("1")) {desfase =2;}
				 if  (session.getAttribute("mes").toString().equals("2")) {desfase =5;}
				 if  (session.getAttribute("mes").toString().equals("3")) {desfase =5;}
				 if  (session.getAttribute("mes").toString().equals("4")) {desfase =1;}
				 if  (session.getAttribute("mes").toString().equals("5")) {desfase =3;}
				 if  (session.getAttribute("mes").toString().equals("6")) {desfase =6;}
				 if  (session.getAttribute("mes").toString().equals("7")) {desfase =1;}
				 if  (session.getAttribute("mes").toString().equals("8")) {desfase =4;}
				 if  (session.getAttribute("mes").toString().equals("9")) {desfase =0;}
				 if  (session.getAttribute("mes").toString().equals("10")) {desfase =2;}
				 if  (session.getAttribute("mes").toString().equals("11")) {desfase =5;}
				 if  (session.getAttribute("mes").toString().equals("12")) {desfase =0;}
			
			
				 String conexion ="jdbc:mysql://localhost:3306/webcalendario";
				
				 Connection connection = null;
				 Class.forName("com.mysql.jdbc.Driver").newInstance();
				
				 connection =DriverManager.getConnection(conexion,"web","calendario");
				 
				 Statement stat = connection.createStatement();
				 ResultSet rset;
				 
				 
				 
				 
				 for(int diavacio =1;diavacio <=desfase;diavacio++){ 
					 out.println("<div class='dia ui-droppable' dia ='' style='position:relative;'><div class='numerodia'><b></b></div>");
					 out.println("</div>");
					  
				} 
				 
				 
					
				 for(int dia =1;dia <=31;dia++){ 
				 String peticion ="select ev.idevento, ev.nombre as nombre, anio,mes,hora,minuto,segundo,duracion,color from eventos  ev,calendarios ca where ev.calendario = ca.idcalendario and   anio='2014' and mes= "+session.getAttribute("mes")+" and dia = "+dia+ " and usuario =" + session.getAttribute("idusuario") + ";";
				 rset = stat.executeQuery(peticion);
				 
				 
				 out.println("<div class='dia ui-droppable' dia ='"+dia+"' style='position:relative;'><div class='numerodia'><b>"+dia+"</b></div>");
				 
				 while(rset.next()){
					 
				 out.println("<div idevento = '"+rset.getString("idevento")+"'  idcaldia='7' anio ='2014' mes='9'  dia ='13' hora='9' nombre='' class='evento ui-draggable' style ='background:rgb("+rset.getString("color")+");width:90%;height:" +rset.getInt("duracion")*0.1+"%;position:absolute;top:"+((rset.getInt("hora")*4)+12)+"%;'>"+rset.getInt("hora")+ "<pan class='motivoevento'>-" +rset.getString("Nombre")+"</span><div class='eliminar'><a style='color=#d7d7d7:'href ='acciones/eliminarEvento.jsp?idevento="+ rset.getInt("idevento") + "'>X</a></div></div>");                                                 
	 							 
				 }	 
				 
				 out.println("</div>");
				  
				  } 
				 				 
				 stat.close();
				 connection.close();
				
					 
			 } catch(Exception ex ){
		
			 out.println("Ha ocurrido el siguiente error"+ ex.getMessage().toString());
			 }
			
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"nuevoevento\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<div id=\"contieneform\">\r\n");
      out.write("\t\t\t\t\t<div id=\"cerrarnuevoevento\">X</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"http://localhost:8080/WebCalendario/acciones/nuevoEvento.jsp\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"anio\" value=\"2014\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"mes\" value=\"9\">\r\n");
      out.write("\t\t\t\t\t\t<h3>Nuevo evento</h3>\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\" id=\"tablanuevoevento\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tbody><tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tAño:\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t2014\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\tMes:\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tSep\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tDia:\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"dia\" id=\"dimedia\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tCalendario:\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"calendario\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t    ");

							 try  {
								 
								 String conexion ="jdbc:mysql://localhost:3306/webcalendario";
								
								 Connection connection = null;
								 Class.forName("com.mysql.jdbc.Driver").newInstance();
								
								 connection =DriverManager.getConnection(conexion,"web","calendario");
								 
								 Statement stat = connection.createStatement();
								 ResultSet rset;
								 
								 String peticion ="SELECT * FROM calendarios";
								 rset = stat.executeQuery(peticion);
								 
								 while(rset.next()){
									 
									  out.println("<option value='"+ rset.getInt("idcalendario") +"'>"+ rset.getString("nombre")+"</option>") ;
								 }	  
								 				 
								 stat.close();
								 connection.close();
								
								 
							 } catch(Exception ex ){
						
							 out.println("Ha ocurrido el siguiente error"+ ex.getMessage().toString());
							 }
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tHora de inicio:\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"hora\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								for (int hora=1;hora<=24;hora++){
									
									out.println("<option value='"+hora+"'>"+hora+"</option>");
								}
								
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t     <!-- <option value=\"0\">0</option><option value=\"1\">1</option><option value=\"2\">2</option><option value=\"3\">3</option><option value=\"4\">4</option><option value=\"5\">5</option><option value=\"6\">6</option><option value=\"7\">7</option><option value=\"8\">8</option><option value=\"9\">9</option><option value=\"10\">10</option><option value=\"11\">11</option><option value=\"12\">12</option><option value=\"13\">13</option><option value=\"14\">14</option><option value=\"15\">15</option><option value=\"16\">16</option><option value=\"17\">17</option><option value=\"18\">18</option><option value=\"19\">19</option><option value=\"20\">20</option><option value=\"21\">21</option><option value=\"22\">22</option><option value=\"23\">23</option><option value=\"24\">24</option>:-->\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t      </select>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<select name=\"minuto\">\r\n");
      out.write("\t\t\t\t\t\t     ");

								for (int minuto=0;minuto<=60;minuto+=5){
									
									out.println("<option value='"+minuto+"'>"+minuto+"</option>");
								}
								
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t     <!--<option value=\"0\">0</option><option value=\"1\">1</option><option value=\"2\">2</option><option value=\"3\">3</option><option value=\"4\">4</option><option value=\"5\">5</option><option value=\"6\">6</option><option value=\"7\">7</option><option value=\"8\">8</option><option value=\"9\">9</option><option value=\"10\">10</option><option value=\"11\">11</option><option value=\"12\">12</option><option value=\"13\">13</option><option value=\"14\">14</option><option value=\"15\">15</option><option value=\"16\">16</option><option value=\"17\">17</option><option value=\"18\">18</option><option value=\"19\">19</option><option value=\"20\">20</option><option value=\"21\">21</option><option value=\"22\">22</option><option value=\"23\">23</option><option value=\"24\">24</option><option value=\"25\">25</option><option value=\"26\">26</option><option value=\"27\">27</option><option value=\"28\">28</option><option value=\"29\">29</option><option value=\"30\">30</option><option value=\"31\">31</option><option value=\"32\">32</option><option value=\"33\">33</option><option value=\"34\">34</option><option value=\"35\">35</option><option value=\"36\">36</option><option value=\"37\">37</option><option value=\"38\">38</option><option value=\"39\">39</option><option value=\"40\">40</option><option value=\"41\">41</option><option value=\"42\">42</option><option value=\"43\">43</option><option value=\"44\">44</option><option value=\"45\">45</option><option value=\"46\">46</option><option value=\"47\">47</option><option value=\"48\">48</option><option value=\"49\">49</option><option value=\"50\">50</option><option value=\"51\">51</option><option value=\"52\">52</option><option value=\"53\">53</option><option value=\"54\">54</option><option value=\"55\">55</option><option value=\"56\">56</option><option value=\"57\">57</option><option value=\"58\">58</option><option value=\"59\">59</option><option value=\"60\">60</option>\t-->\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tDuración:\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"duracion\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">0</option><option value=\"30\">0:30</option><option value=\"60\">1</option><option value=\"90\">1:30</option><option value=\"120\">2</option><option value=\"150\">2:30</option><option value=\"180\">3</option><option value=\"210\">3:30</option><option value=\"240\">4</option><option value=\"270\">4:30</option><option value=\"300\">5</option><option value=\"330\">5:30</option><option value=\"360\">6</option><option value=\"390\">6:30</option><option value=\"420\">7</option><option value=\"450\">7:30</option><option value=\"480\">8</option><option value=\"510\">8:30</option><option value=\"540\">9</option><option value=\"570\">9:30</option><option value=\"600\">10</option><option value=\"630\">10:30</option><option value=\"660\">11</option><option value=\"690\">11:30</option><option value=\"720\">12</option><option value=\"750\">12:30</option><option value=\"780\">13</option><option value=\"810\">13:30</option><option value=\"840\">14</option><option value=\"870\">14:30</option><option value=\"900\">15</option><option value=\"930\">15:30</option><option value=\"960\">16</option><option value=\"990\">16:30</option><option value=\"1020\">17</option><option value=\"1050\">17:30</option><option value=\"1080\">18</option><option value=\"1110\">18:30</option><option value=\"1140\">19</option><option value=\"1170\">19:30</option><option value=\"1200\">20</option><option value=\"1230\">20:30</option><option value=\"1260\">21</option><option value=\"1290\">21:30</option><option value=\"1320\">22</option><option value=\"1350\">22:30</option><option value=\"1380\">23</option><option value=\"1410\">23:30</option>\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\tNombre del evento:\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"nombre\" placeholder=\"nombre\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody></table>\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"nuevocalendarioforma\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<div id=\"contieneform\">\r\n");
      out.write("\t\t\t\t\t<div id=\"cerrarnuevocalendario\">X</div>\r\n");
      out.write("\t\t\t\t\t<form action=\"http://localhost:8080/WebCalendario/acciones/nuevoCalendario.jsp\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"anio\" value=\"2014\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"mes\" value=\"9\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t   <input type=\"text\"   name =\"nombrecalendario\"> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t   <input type =\"submit\"> \t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"ajax\"></div>\r\n");
      out.write("\t\r\n");
      out.write("</body></html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
